### ISSUE TITLE
请问关于添加的临时数据,怎么保存到绑定的data呢?

### ISSUE THREAD

**Issue by ken1691** [xuliangzhan/vxe-table-demo#2]
怎么保存新插入的数据到绑定的data呢?

https://xuliangzhan.github.io/vxe-table/#/table/edit/insert

文档的demo里面,保存的例子是获取新数据 . 

`
            getInsertEvent () {
              let insertRecords = this.$refs.xTable.getInsertRecords()
              this.$XModal.alert(insertRecords.length)
            }`

研究了一天也没有弄明白,
于是用笨办法,拿到新数据处理后push到data内了.

作者大大可否帮忙解答一下.   万分感谢~!

**Comment by xuliangzhan** [comment]
插入到 data 中不就是 thi.tableData.push({})
